#!/bin/bash
# Replit Deployment Build Script
# This script ensures dist/index.js is created correctly for deployment

echo "🚀 Starting Replit deployment build..."

# Step 1: Clean dist directory
echo "📦 Cleaning dist directory..."
rm -rf dist
mkdir -p dist

# Step 2: Build server with correct output file
echo "🔧 Building server to dist/index.js..."
npx esbuild server/index.ts \
  --platform=node \
  --packages=external \
  --bundle \
  --format=esm \
  --outfile=dist/index.js \
  --banner:js="// Generated by Replit deployment build"

if [ ! -f "dist/index.js" ]; then
  echo "❌ Error: dist/index.js was not created"
  exit 1
fi

# Step 3: Build frontend
echo "🎨 Building frontend..."
npx vite build --outDir=client/dist

# Step 4: Copy frontend to dist/public for server serving
echo "📂 Setting up frontend files..."
mkdir -p dist/public
cp -r client/dist/* dist/public/
cp -r client/dist/* dist/

# Step 5: Create ESM package.json
echo "📝 Creating dist/package.json..."
echo '{"type":"module"}' > dist/package.json

# Step 6: Verify build
echo "✅ Verifying build output..."
if [ -f "dist/index.js" ]; then
  SIZE=$(stat -c%s "dist/index.js" 2>/dev/null || stat -f%z "dist/index.js" 2>/dev/null || echo "unknown")
  echo "✓ Server bundle: dist/index.js ($SIZE bytes)"
else
  echo "❌ FAILURE: dist/index.js not found!"
  exit 1
fi

if [ -f "dist/index.html" ]; then
  echo "✓ Frontend entry: dist/index.html"
else
  echo "⚠️  Warning: dist/index.html not found"
fi

if [ -f "dist/public/index.html" ]; then
  echo "✓ Public frontend: dist/public/index.html"
else
  echo "⚠️  Warning: dist/public/index.html not found"
fi

echo ""
echo "🎉 Build completed successfully!"
echo "📋 Deployment ready:"
echo "   Entry point: dist/index.js"
echo "   Start command: node dist/index.js"
echo ""