// Placeholder for missing images - use SVG placeholders instead
export const fundTekLogo = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIyMDAiIGhlaWdodD0iODAiIHJ4PSI4IiBmaWxsPSIjMzM3M2RjIi8+PHRleHQgeD0iMTAwIiB5PSI0NSIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjE4IiBmaWxsPSJ3aGl0ZSIgdGV4dC1hbmNob3I9Im1pZGRsZSI+RnVuZFRlayBDYXBpdGFsPC90ZXh0Pjwvc3ZnPg==";

export const placeholderImage = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAwIiBoZWlnaHQ9IjQwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZjNmNGY2Ii8+CiAgPHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxOCIgZmlsbD0iIzllYTNhOCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkZ1bmRUZWsgSW1hZ2U8L3RleHQ+Cjwvc3ZnPg==";

// All the specific images that were being imported
export const truckImage = placeholderImage;
export const debtConsolidationImage = placeholderImage;
export const mortgageImage = placeholderImage;
export const termLoanImage = placeholderImage;
export const lineOfCreditImage = placeholderImage;
export const paymentImage = placeholderImage;
export const digitalImage = placeholderImage;
export const logoPath = fundTekLogo;
export const heroBackgroundPath = placeholderImage;
